databases:
  - name: healthcare-db
    databaseName: healthcare
    plan: free

services:
  # 1. Gateway
  - type: web
    name: healthcare-gateway
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080

  # 2. Security
  - type: web
    name: healthcare-security
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8081

  # 3. Patient Service
  - type: web
    name: healthcare-patient
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8082

  # 4. Doctor Service
  - type: web
    name: healthcare-doctor
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8083

  # 5. Appointment Service
  - type: web
    name: healthcare-appointment
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8084

  # 6. Billing Service
  - type: web
    name: healthcare-billing
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8085

  # 7. Pharmacy Service
  - type: web
    name: healthcare-pharmacy
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8086

  # 8. Main HealthCare Service
  - type: web
    name: healthcare-main
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8087

  # Frontend (Guaranteed Node server)
  - type: web
    name: healthcare-ui
    env: node
    plan: free
    buildCommand: cd healthcare-ui && npm install && npm run build
    startCommand: cd healthcare-ui && npx serve -s dist/healthcare-ui/browser
    envVars:
      - key: PORT
        value: 10000
