spring:
  application:
    name: healthcare-gateway
  cloud:
    gateway:
      routes:

        # AUTH SERVICE
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/login,/api/register
          filters:
            - StripPrefix=1

        # PATIENT SERVICE
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/patients,/api/patients/**

        # DOCTOR SERVICE
        - id: doctor-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/doctors,/api/doctors/**

server:
  port: 8080